name: "🚨 버그 리포트"
description: "버그가 발생했어요"
title: "[🐞 Bug] "
labels: "🐞 Bug"
assignees: ["chltmdgh522"]
body:
  - type: textarea
    attributes:
      label: 🐞설명
      description: 버그에 대한 설명을 작성해 주세요.
      placeholder: 꼼꼼하게 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ⛰️ 맥락
      description: 버그가 발생한 맥락(=재현 방법)을 작성해 주세요.
      placeholder: |
        1. 회원가입을 한다.
        2. 새로운 창으로 이동한다.
        3. "로그인을 할 수 없습니다."라는 메시지가 뜬다.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🌏 환경
      description: 버그가 발생한 환경에 대해 작성해 주세요.
      placeholder: |
        OS: macOS 12.2.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📄 로그
      description: 로그 있으면 복붙해 주세요.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🙋🏻 덧붙일 말
      description: 더 하고 싶은 말이 있다면 작성해 주세요.